import Joi from "joi-browser";
const schema = {
  lbl: Joi.string().required(),
  ts: Joi.number().min(0),
  ps: Joi.number().min(0),
  ns: Joi.number().min(0),
  tp: Joi.number().min(0),
  fp: Joi.number().min(0),
  fn: Joi.number().min(0),
  tn: Joi.number().min(0),
  rc: Joi.number().min(0).max(1),
  prc: Joi.number().min(0).max(1),
  f1: Joi.number().min(0).max(1),
  acc: Joi.number().min(0).max(1),
  spf: Joi.number().min(0).max(1),
  mcc: Joi.number().min(-1).max(1),
  npv: Joi.number().min(0).max(1),
  ths: Joi.number().min(0).max(1),
  err: Joi.object().optional(),
  tsLock: Joi.boolean(),
  psLock: Joi.boolean(),
  nsLock: Joi.boolean(),
  tpLock: Joi.boolean(),
  fnLock: Joi.boolean(),
  tnLock: Joi.boolean(),
  fpLock: Joi.boolean(),
  rcLock: Joi.boolean(),
  prcLock: Joi.boolean(),
  f1Lock: Joi.boolean(),
  accLock: Joi.boolean(),
  mccLock: Joi.boolean(),
  spfLock: Joi.boolean(),
  npvLock: Joi.boolean(),
  thsLock: Joi.boolean(),
};
export { schema };
